name: Nix

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/flake-checker-action@v5
        with:
          fail-mode: true
      - run: nix flake check --all-systems

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04 # linux x86_64
          - macos-12 # macOS x86_64
          - macos-14 # macOS arm64
        package:
          - dakara_check
          - ffmpegaacsucks
          - syncplay
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - run: nix build -L .#${{ matrix.package }}
